version: "2"
services:
  adsbexchange:
    image: bradsjm/adsbexchange
    build: ./adsbexchange
    read_only: true
    restart: unless-stopped
    environment:
      - DUMP1090_SERVER=dump1090
      - DUMP1090_PORT=30005
      - ADSBEXCHANGE_PORT=30005
    depends_on:
      - dump1090

  adsbexchange-mlat:
    image: bradsjm/adsbexchange-mlat
    build: ./adsbexchange-mlat
    read_only: true
    restart: unless-stopped
    ports:
      - "30104:30104/tcp"
    environment:
      - LATITUDE=
      - LONGITUDE=
      - ALTITUDE=
      - MLAT_CLIENT_USER=
    depends_on:
      - dump1090

  adsbhub:
    image: bradsjm/adsbhub
    build: ./adsbhub
    read_only: true
    restart: unless-stopped
    depends_on:
      - dump1090

  #  datadog:
  #    image: bradsjm/balena-datadog
  #    build: ./balena-datadog
  #    restart: unless-stopped
  #    privileged: true
  #    pid: host
  #    network_mode: host
  #    environment:
  #      - DD_API_KEY=
  #      - DD_LOGS_ENABLED=true
  #      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
  #      - DOCKER_HOST=unix:///var/run/balena.sock
  #      - DOCKER_SOCKET_PATH=/var/run/balena.sock
  #    labels:
  #      io.resin.features.dbus: 1
  #      io.resin.features.balena-socket: 1

  direwolf:
    image: bradsjm/direwolf
    build: ./direwolf
    restart: unless-stopped
    devices:
      - "/dev/bus/usb"
    environment:
      - DEVICE=1
      - MYCALL=n0call
      - IGLOGIN=n0call -1
      - IGSERVER=noam.aprs2.net
      - FREQUENCY=144.39M

  dump1090:
    image: bradsjm/dump1090
    build: ./dump1090
    restart: unless-stopped
    environment:
      - DEVICE=00001000
    ports:
      - "30002:30002/tcp"
      - "30003:30003/tcp"
      - "30005:30005/tcp"
    devices:
      - "/dev/bus/usb"
    cap_add:
      - SYS_NICE

  flightaware:
    image: bradsjm/flightaware
    build: ./flightaware
    restart: unless-stopped
    ports:
      - "30105:30105/tcp"
    environment:
      - FLIGHTAWARE_USERNAME=
      - FLIGHTAWARE_PASSWORD=
      - FLIGHTAWARE_FEEDER_ID=
      - FLIGHTAWARE_GPS_HOST=
    depends_on:
      - dump1090

  flightradar24:
    image: bradsjm/flightradar24
    build: ./flightradar24
    restart: unless-stopped
    environment:
      - FR24FEED_KEY=
    ports:
      - "8754:8754/tcp"
    depends_on:
      - dump1090

  glances:
    image: bradsjm/glances
    build: ./glances
    privileged: true
    pid: host
    network_mode: host
    tmpfs:
      - /tmp:mode=1777
      - /run:mode=1777
    environment:
      - DOCKER_HOST=unix:///var/run/balena.sock
      - GLANCES_OPT=-w
    labels:
      io.resin.features.dbus: 1
      io.resin.features.balena-socket: 1

  modesmixer2:
    image: bradsjm/modesmixer2
    build: ./modesmixer2
    restart: unless-stopped
    ports:
      - "80:8080/tcp"
    environment:
      - DUMP1090_HOST=dump1090
      - DUMP1090_PORT=30005
      - LATITUDE=
      - LONGITUDE=
      - GOOGLE_KEY=
    depends_on:
      - dump1090

  openskynetwork:
    image: bradsjm/openskynetwork
    build: ./openskynetwork
    restart: unless-stopped
    ports:
      - "30975:30005/tcp"
    environment:
      - DUMP1090_HOST=dump1090
      - DUMP1090_PORT=30005
      - LATITUDE=
      - LONGITUDE=
      - ALTITUDE=
      - OPENSKY_USER=
      - OPENSKY_SERIAL=
    depends_on:
      - dump1090

  planefinder:
    image: bradsjm/planefinder
    build: ./planefinder
    restart: unless-stopped
    ports:
      - "30053:30053/tcp"
    environment:
      - DUMP1090_HOST=dump109
      - DUMP1090_PORT=30005
      - LATITUDE=
      - LONGITUDE=
      - PLANEFINDER_SHARECODE=
    depends_on:
      - dump1090

  radarbox24:
    image: bradsjm/radarbox24
    build: ./radarbox24
    restart: unless-stopped
    environment:
      - DUMP1090_HOST=dump109
      - DUMP1090_PORT=30005
      - DUMP1090_PROTOCOL=beast
      - RADARBOX24_KEY=
    depends_on:
      - dump1090
