version: "2"
services:
  dump1090:
    build: ./dump1090
    restart: always
    command: "--device 00001000"
    ports:
      - "30002:30002/tcp"
      - "30003:30003/tcp"
      - "30005:30005/tcp"
    devices:
      - "/dev/bus/usb"
    cap_add:
      - SYS_NICE

  flightradar24:
    build: ./flightradar24
    restart: always
    environment:
      - "FR24FEED_KEY="
    ports:
      - "8754:8754/tcp"
    depends_on:
      - dump1090
