version: "2"
services:
  dump1090:
    build: ./dump1090
    restart: unless-stopped
    command: "--device 00001000"
    ports:
      - "30002:30002/tcp"
      - "30003:30003/tcp"
      - "30005:30005/tcp"
    devices:
      - "/dev/bus/usb"
    cap_add:
      - SYS_NICE

  flightradar24:
    build: ./flightradar24
    restart: unless-stopped
    environment:
      - "FR24FEED_KEY="
    ports:
      - "8754:8754/tcp"
    depends_on:
      - dump1090

  modesmixer2:
    build: ./modesmixer2
    restart: unless-stopped
    ports:
      - "8081:8080/tcp"
    command:
      - '--inConnectId'
      - 'dump1090:30005:DUMP1090'
      - '--inConnectId'
      - 'flightaware:30105:MLAT'
      - '--location'
      - 'XXXX:XXXX'
      - '--google-key'
      - 'XXXX'
    depends_on:
      - dump1090

  planefinder:
    build: ./planefinder
    restart: unless-stopped
    ports:
      - "30053:30053/tcp"
    environment:
      - PLANEFINDER_SHARECODE=XXXX
      - PLANEFINDER_LATITUDE=XXXX
      - PLANEFINDER_LONGITUDE=XXXX
    depends_on:
      - dump1090

  adsbexchange:
    build: ./adsbexchange
    restart: unless-stopped
    environment:
      - DUMP1090_SERVER=dump1090
      - DUMP1090_PORT=30005
      - ADSBEXCHANGE_PORT=30005
    depends_on:
      - dump1090
