version: "2"
services:
  netdata:
    image: netdata/netdata
    hostname: $HOSTNAME
    ports:
      - "19999:19999/tcp"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - "PGID=999"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  dump1090:
    build: ./dump1090
    restart: unless-stopped
    command: "--device 00001000"
    ports:
      - "30002:30002/tcp"
      - "30003:30003/tcp"
      - "30005:30005/tcp"
    devices:
      - "/dev/bus/usb"
    cap_add:
      - SYS_NICE

  flightradar24:
    build: ./flightradar24
    restart: unless-stopped
    environment:
      - "FR24FEED_KEY="
    ports:
      - "8754:8754/tcp"
    depends_on:
      - dump1090

  modesmixer2:
    build: ./modesmixer2
    restart: unless-stopped
    ports:
      - "8081:8080/tcp"
    command:
      - "--inConnectId"
      - "dump1090:30005:DUMP1090"
      - "--inConnectId"
      - "flightaware:30105:MLAT"
      - "--location"
      - "XXXX:XXXX"
      - "--google-key"
      - "XXXX"
    depends_on:
      - dump1090

  planefinder:
    build: ./planefinder
    restart: unless-stopped
    ports:
      - "30053:30053/tcp"
    environment:
      - PLANEFINDER_SHARECODE=XXXX
      - PLANEFINDER_LATITUDE=XXXX
      - PLANEFINDER_LONGITUDE=XXXX
    depends_on:
      - dump1090

  adsbexchange:
    build: ./adsbexchange
    restart: unless-stopped
    environment:
      - DUMP1090_SERVER=dump1090
      - DUMP1090_PORT=30005
      - ADSBEXCHANGE_PORT=30005
    depends_on:
      - dump1090

  adsbexchange-mlat:
    build: ./adsbexchange-mlat
    restart: unless-stopped
    ports:
      - "30104:30104/tcp"
    environment:
      - MLAT_CLIENT_LATITUDE=XXXX
      - MLAT_CLIENT_LONGITUDE=XXXX
      - MLAT_CLIENT_ALTITUDE=XXXX
      - MLAT_CLIENT_USER=XXXX
    depends_on:
      - dump1090

  adsbhub:
    build: ./adsbhub
    container_name: "adsbhub"
    restart: unless-stopped
    depends_on:
      - dump1090

  openskynetwork:
    build: ./openskynetwork
    restart: unless-stopped
    ports:
      - "30975:30005/tcp"
    environment:
      - OPENSKY_LATITUDE=XXXX
      - OPENSKY_LONGITUDE=XXXX
      - OPENSKY_ALTITUDE=XXXX
      - OPENSKY_USER=bXXXX
      - OPENSKY_SERIAL=XXXX
      - DUMP1090_HOST=dump1090
      - DUMP1090_PORT=30005
    depends_on:
      - dump1090

  flightaware:
    build: ./flightaware
    restart: unless-stopped
    ports:
      - "30105:30105/tcp"
    environment:
      - FLIGHTAWARE_USERNAME=XXXX
      - FLIGHTAWARE_PASSWORD=XXXX
      - FLIGHTAWARE_FEEDER_ID=XXXX
      - FLIGHTAWARE_GPS_HOST=
    depends_on:
      - dump1090

  radarbox24:
    build: ./radarbox24
    restart: unless-stopped
    environment:
      - DUMP1090_HOST=dump1090
      - DUMP1090_PORT=30005
      - DUMP1090_PROTOCOL=beast
      - RADARBOX24_KEY=XXXX
    depends_on:
      - dump1090

  direwolf:
    build: ./direwolf
    restart: unless-stopped
