version: "2"
services:
  datadog:
    image: achntrl/datadog-agent
    restart: unless-stopped
    privileged: true
    pid: host
    network_mode: host
    environment:
      - "DOCKER_SOCKET_PATH=/var/run/balena.sock"
      - "DD_APM_ENABLED=false"
    labels:
      io.resin.features.dbus: 1
      io.resin.features.balena-socket: 1

  dump1090:
    build: ./dump1090
    restart: unless-stopped
    command: "--device 00001000"
    ports:
      - "30002:30002/tcp"
      - "30003:30003/tcp"
      - "30005:30005/tcp"
    devices:
      - "/dev/bus/usb"
    cap_add:
      - SYS_NICE

  flightradar24:
    build: ./flightradar24
    restart: unless-stopped
    environment:
      - "FR24FEED_KEY="
    ports:
      - "8754:8754/tcp"
    depends_on:
      - dump1090

  modesmixer2:
    build: ./modesmixer2
    restart: unless-stopped
    ports:
      - "8081:8080/tcp"
    command:
      - "--inConnectId"
      - "dump1090:30005:DUMP1090"
      - "--inConnectId"
      - "flightaware:30105:MLAT"
      - "--location"
      - "${LATITUDE}:${LONGITUDE}"
      - "--google-key"
      - "${GOOGLE_KEY}"
    depends_on:
      - dump1090

  planefinder:
    build: ./planefinder
    restart: unless-stopped
    ports:
      - "30053:30053/tcp"
    environment:
      - LATITUDE=
      - LONGITUDE=
      - PLANEFINDER_SHARECODE=
    depends_on:
      - dump1090

  adsbexchange:
    build: ./adsbexchange
    restart: unless-stopped
    environment:
      - DUMP1090_SERVER=dump1090
      - DUMP1090_PORT=30005
      - ADSBEXCHANGE_PORT=30005
    depends_on:
      - dump1090

  adsbexchange-mlat:
    build: ./adsbexchange-mlat
    restart: unless-stopped
    ports:
      - "30104:30104/tcp"
    environment:
      - LATITUDE=
      - LONGITUDE=
      - ALTITUDE=
      - MLAT_CLIENT_USER=
    depends_on:
      - dump1090

  adsbhub:
    build: ./adsbhub
    container_name: "adsbhub"
    restart: unless-stopped
    depends_on:
      - dump1090

  openskynetwork:
    build: ./openskynetwork
    restart: unless-stopped
    ports:
      - "30975:30005/tcp"
    environment:
      - LATITUDE=
      - LONGITUDE=
      - ALTITUDE=
      - OPENSKY_USER=
      - OPENSKY_SERIAL=
      - DUMP1090_HOST=dump1090
      - DUMP1090_PORT=30005
    depends_on:
      - dump1090

  flightaware:
    build: ./flightaware
    restart: unless-stopped
    ports:
      - "30105:30105/tcp"
    environment:
      - FLIGHTAWARE_USERNAME=
      - FLIGHTAWARE_PASSWORD=
      - FLIGHTAWARE_FEEDER_ID=
      - FLIGHTAWARE_GPS_HOST=
    depends_on:
      - dump1090

  radarbox24:
    build: ./radarbox24
    restart: unless-stopped
    environment:
      - DUMP1090_HOST=dump1090
      - DUMP1090_PORT=30005
      - DUMP1090_PROTOCOL=beast
      - RADARBOX24_KEY=
    depends_on:
      - dump1090

  direwolf:
    build: ./direwolf
    restart: unless-stopped
    devices:
      - "/dev/bus/usb"
    command: "-d 1"
    environment:
      - MYCALL n0call
      - IGLOGIN n0call -1
      - IGSERVER=noam.aprs2.net
      - FREQUENCY=144.39M
